import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { serveWorkspace, writeJson, readWorkspace, normalizeVideo, importVideoWorkspace, importVideo, probeVideo, bundleVideoEdit, runProcess, verifyMatteEdit } from '../packages/runtime/src/index';
import { parseWorkspace, planAction, applyDocumentEdit, planDocumentEdit } from '../packages/harness/src/index';
const dir = await mkdtemp(join(tmpdir(),'cassie-integration-'));
let server: Awaited<ReturnType<typeof serveWorkspace>> | undefined;
try {
 const file=join(dir,'project.json');
 await writeJson(file,parseWorkspace(await readFile(new URL('../examples/action-flow/project.cassie.json',import.meta.url),'utf8')));
 server=await serveWorkspace(file,0);
 const get=async(path:string)=>(await fetch(server!.url+path)).json();
 const initial=await get('/api/project');
 const post=async(path:string,body:unknown,token=initial.token)=>fetch(server!.url+path,{method:'POST',headers:{'Content-Type':'application/json','X-Cassie-Token':token},body:JSON.stringify(body)});
 assert.equal((await fetch(server.url)).status,200);
 assert.equal((await post('/api/edit',{},'bad')).status,403);
 const response=await post('/api/edit',{revision:0,edit:{kind:'set-event-timing',eventId:'greeting',startFrame:30,durationFrames:60}});
 assert.equal(response.status,200);const moved=await response.json();
 assert.deepEqual(moved.document.events[0].start,{frame:30});
 assert.equal(moved.document.events[0].durationOverrideFrames,undefined);
 assert.equal((await get('/api/project')).events.find((e:any)=>e.id==='product-reveal').startFrame,96);
 assert.equal((await post('/api/edit',{revision:0,edit:{kind:'set-layer',layerId:'actor',patch:{x:200}}})).status,400);
 const persisted=await readWorkspace(file);assert.equal(persisted.document.editor.revision,1);
 const plan=(await (await post('/api/plan',{kind:'set-action-state',eventId:'greeting',state:'point'})).json()).plan;
 assert.equal(plan.changes.find((e:any)=>e.eventId==='product-reveal').after.startFrame,126);
 assert.equal((await post('/api/apply',{plan})).status,200);
 assert.equal((await post('/api/rollback',{id:plan.id})).status,200);
 assert.equal((await post('/api/rollback',{id:moved.transactions[0].id})).status,200);
 const restored=await readWorkspace(file);assert.equal(restored.document.editor.revision,4);
 assert.deepEqual(restored.document.events,initial.workspace.document.events);
 const source=join(dir,'synthetic-source.mp4'),normalized=join(dir,'cfr.mp4');
 await runProcess('ffmpeg',['-hide_banner','-loglevel','error','-n','-f','lavfi','-i','testsrc2=size=160x240:rate=12:duration=4','-f','lavfi','-i','sine=frequency=440:sample_rate=32000:duration=4','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-shortest',source]);
 const normalization=await normalizeVideo(source,normalized,24);assert.equal(normalization.frames,96);
 const video=await importVideoWorkspace(normalized,join(dir,'video.json'),{entity:'Synthetic fixture',instruction:'Contract test only',cuts:[24,72]});
 assert.equal(video.document.events.filter(e=>e.kind==='sound').length,3);assert.deepEqual(video.document.events[1]!.start,{eventId:'person-action',edge:'end',offsetFrames:0});
 const maskFile=join(dir,'synthetic-mask.mp4');
 await runProcess('ffmpeg',['-hide_banner','-loglevel','error','-n','-f','lavfi','-i','color=white:size=160x240:rate=24:duration=1','-c:v','libx264','-qp','0','-pix_fmt','yuv420p',maskFile]);
 const mask=await importVideo(dir,maskFile);
 const maskEdit={kind:'attach-subject-matte' as const,eventId:'person-action',asset:{id:'test-mask',kind:'video' as const,name:'Synthetic full-frame mask, not segmentation',durationUs:1_000_000,width:160,height:240},media:mask.media,matte:{entityId:'person',eventId:'person-action',sourceAssetId:'source',sourceSha256:video.document.media.source!.sha256,sourceStartFrame:0,frames:24,width:160,height:240,frameRate:{num:24,den:1},maskAssetId:'test-mask',backend:'test-no-segmentation',quality:'draft' as const}};
 await verifyMatteEdit(video.document,dir,maskEdit);
 const masked=applyDocumentEdit(video,planDocumentEdit(video.document,maskEdit));
 const actionPlan=planAction(masked.document,{kind:'set-action-state',eventId:'person-action',state:'custom',instruction:'Synthetic contract test, not an actual generated action',durationFrames:36});
 const bundle=join(dir,'model-bundle');await bundleVideoEdit(masked.document,dir,actionPlan,bundle);
 assert.equal((await probeVideo(join(bundle,'task-1/source.mp4'))).frames,24);assert.equal((await probeVideo(join(bundle,'task-1/mask.mp4'))).frames,24);
 const request=JSON.parse(await readFile(join(bundle,'task-1/request.json'),'utf8'));assert.equal(request.output.frames,36);assert.equal(request.status,'awaiting-provider');
 assert.equal(actionPlan.changes.find(c=>c.eventId==='shot-2')!.after.startFrame,36);
 const changed=structuredClone(masked.document);changed.editor.revision++;
 await assert.rejects(()=>bundleVideoEdit(changed,dir,actionPlan,join(dir,'stale-bundle')),/unchanged/);
 console.log('Media integration passed: CFR normalization, shot/audio graph, hashed mask validation, source/mask bundle, requested output domain, stale-plan rejection.');
 console.log('HTTP integration passed: auth, timing cascade, persistence, stale edit, action recompute, sequential undo.');
} finally { server?.close();await rm(dir,{recursive:true,force:true}); }
